### ISSUE TITLE
will the documentation be updated?

### ISSUE THREAD

**Issue by coding9991** [lssac7778/Off-road-Benchmark#1]
Thank you very much for your excellent work,
I'm going to do some experimentation in this benchmark, will the documentation be updated?
best regards.

**Comment by isaac7778** [comment]
Sorry for late. The documentation will be uploaded until this month.

**Comment by isaac7778** [comment]
@feelinggxj 
Sorry for late.
Document is ready [here](https://github.com/lssac7778/Off-road-Benchmark/wiki)
If you need any help please contact lssac7778@gm.gist.ac.kr
